In [2]:
import numpy as np

In [3]:
list = [1,2,3,4,5]
arr=np.array(list)
arr

array([1, 2, 3, 4, 5])

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.random.randint(1,10)

4

In [25]:
np.random.randint(1,20,(2,3))

array([[ 8,  7,  5],
       [18, 13, 15]])

In [51]:
np.random.seed(150)
np.random.randint(1,50,7)

array([37, 26, 49, 37, 15, 38, 24])

In [52]:
arr.max()

49

In [53]:
arr.min()

15

In [54]:
arr.mean()

32.285714285714285

In [56]:
arr.argmax()

2

In [57]:
arr.argmin()

4

In [64]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
mat[1,3]

9

In [69]:
mat[:0]

array([], shape=(0, 5), dtype=int32)

In [70]:
mat[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
mat[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [73]:
mat[:,0]

array([ 1,  6, 11, 16, 21])

In [74]:
mat[1,:]   #row

array([ 6,  7,  8,  9, 10])

In [75]:
mat[:,0]   #coloum

array([ 1,  6, 11, 16, 21])

In [78]:
mat[0:4,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [80]:
mat[4,3]

24

In [81]:
np.sqrt(mat)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ]])

In [82]:
np.std(mat)  #standerd deviation

7.211102550927978

In [86]:
# numpy operation

A = np.array([(1,2,3),(3,4,5)])
B = np.array([(1,2,4),(3,4,6)])

In [89]:
A+B

array([[ 2,  4,  7],
       [ 6,  8, 11]])

In [90]:
A*B

array([[ 1,  4, 12],
       [ 9, 16, 30]])

In [92]:
np.vstack((A,B))

array([[1, 2, 3],
       [3, 4, 5],
       [1, 2, 4],
       [3, 4, 6]])

In [ ]:
# SPACIAL FUNCTION
